const EKKVASTRA_PRODUCTS = [
    {
        id: 1,
        name: "Signature Oversized Hoodie - Black",
        category: "Hoodies",
        fit: "Oversized",
        gender: "Unisex",
        price: 1799,
        oldPrice: 2299,
        image: "images/ekkvastra_hoodie.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#111111", "#8a8a8a", "#d8d0c4"],
        colorsName: ["black", "gray", "beige"],
        sizes: ["S", "M", "L", "XL"],
        rating: { stars: 5, count: 128 },
        inStock: true,
        date: "2026-06-25",
        sales: 340,
        badge: "Best Seller"
    },
    {
        id: 2,
        name: "Abstract Graphic Tee - Sand",
        category: "Graphic Tees",
        fit: "Oversized",
        gender: "Unisex",
        price: 999,
        image: "images/ekkvastra_front_print_tee.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#d8d0c4", "#111111"],
        colorsName: ["beige", "black"],
        sizes: ["XS", "S", "M", "L"],
        rating: { stars: 5, count: 96 },
        inStock: true,
        date: "2026-06-20",
        sales: 220
    },
    {
        id: 3,
        name: "Cargo Parachute Pants - Ash Grey",
        category: "Cargo Pants",
        fit: "Relaxed",
        gender: "Men",
        price: 1699,
        oldPrice: 1999,
        image: "images/ekkvastra_cargo.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#8a8a8a", "#111111", "#5c5a52"],
        colorsName: ["gray", "black", "olive"],
        sizes: ["S", "M", "L", "XL"],
        rating: { stars: 4, count: 88 },
        inStock: true,
        date: "2026-05-18",
        sales: 290,
        badge: "-15%"
    },
    {
        id: 4,
        name: "Graphic Tee - Sketch Noir",
        category: "Graphic Tees",
        fit: "Oversized",
        gender: "Unisex",
        price: 1299,
        image: "images/graphic_tee_noir.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#111111", "#ffffff"],
        colorsName: ["black", "white"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        rating: { stars: 5, count: 59 },
        inStock: true,
        date: "2026-06-28",
        sales: 110,
        badge: "New"
    },
    {
        id: 5,
        name: "Minimal Tee - Core Sand",
        category: "Oversized Tees",
        fit: "Oversized",
        gender: "Unisex",
        price: 1099,
        image: "images/minimal_tee_sand.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#d8d0c4", "#111111", "#8a8a8a"],
        colorsName: ["beige", "black", "gray"],
        sizes: ["XS", "S", "M", "L", "XL"],
        rating: { stars: 5, count: 112 },
        inStock: true,
        date: "2026-06-15",
        sales: 310
    },
    {
        id: 6,
        name: "Zip Hoodie - Slate Charcoal",
        category: "Hoodies",
        fit: "Regular",
        gender: "Unisex",
        price: 1799,
        image: "images/zip_hoodie_charcoal.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#4d4d4d", "#111111"],
        colorsName: ["gray", "black"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        rating: { stars: 4, count: 76 },
        inStock: true,
        date: "2026-06-10",
        sales: 180
    },
    {
        id: 7,
        name: "Joggers - Grey Melange",
        category: "Joggers",
        fit: "Relaxed",
        gender: "Unisex",
        price: 1499,
        image: "images/joggers_grey.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#8a8a8a", "#111111", "#d8d0c4"],
        colorsName: ["gray", "black", "beige"],
        sizes: ["S", "M", "L", "XL"],
        rating: { stars: 5, count: 110 },
        inStock: true,
        date: "2026-06-05",
        sales: 215
    },
    {
        id: 8,
        name: "Heavyweight Boxy Sweatshirt",
        category: "Sweatshirts",
        fit: "Oversized",
        gender: "Unisex",
        price: 1599,
        image: "images/boxy_sweatshirt.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#d8d0c4", "#8a8a8a"],
        colorsName: ["beige", "gray"],
        sizes: ["S", "M", "L", "XL"],
        rating: { stars: 5, count: 55 },
        inStock: true,
        date: "2026-06-12",
        sales: 130
    },
    {
        id: 9,
        name: "Distressed Utility Cargo Shorts",
        category: "Shorts",
        fit: "Relaxed",
        gender: "Men",
        price: 1299,
        image: "images/cargo_shorts.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#5c5a52", "#8a8a8a"],
        colorsName: ["olive", "gray"],
        sizes: ["S", "M", "L"],
        rating: { stars: 4, count: 48 },
        inStock: true,
        date: "2026-05-25",
        sales: 120
    },
    {
        id: 10,
        name: "Nylon Utility Track Jacket",
        category: "Jackets",
        fit: "Regular",
        gender: "Men",
        price: 2499,
        image: "images/track_jacket.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#111111", "#5c5a52"],
        colorsName: ["black", "olive"],
        sizes: ["S", "M", "L", "XL"],
        rating: { stars: 5, count: 32 },
        inStock: true,
        date: "2026-06-22",
        sales: 75
    },
    {
        id: 11,
        name: "Minimalist Utility Backpack",
        category: "Accessories",
        fit: "Slim",
        gender: "Unisex",
        price: 2299,
        image: "images/utility_backpack.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#111111", "#8a8a8a"],
        colorsName: ["black", "gray"],
        sizes: ["S", "M", "L"],
        rating: { stars: 5, count: 24 },
        inStock: false,
        date: "2026-05-10",
        sales: 50
    },
    {
        id: 12,
        name: "Signature Streetwear Bucket Hat",
        category: "Accessories",
        fit: "Regular",
        gender: "Unisex",
        price: 699,
        image: "images/bucket_hat.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#111111", "#ffffff"],
        colorsName: ["black", "white"],
        sizes: ["XS", "S", "M", "L", "XL"],
        rating: { stars: 4, count: 18 },
        inStock: true,
        date: "2026-06-08",
        sales: 140
    },
    {
        id: 13,
        name: "Acid Wash Graphic Tee",
        category: "Graphic Tees",
        fit: "Oversized",
        gender: "Unisex",
        price: 1199,
        image: "images/ekkvastra_front_print_tee.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#4d4d4d", "#111111"],
        colorsName: ["gray", "black"],
        sizes: ["M", "L", "XL"],
        rating: { stars: 5, count: 64 },
        inStock: true,
        date: "2026-06-24",
        sales: 165
    },
    {
        id: 14,
        name: "Women's Cropped Hoodie - Beige",
        category: "Hoodies",
        fit: "Relaxed",
        gender: "Women",
        price: 1599,
        image: "images/ekkvastra_hoodie.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#d8d0c4", "#ffffff"],
        colorsName: ["beige", "white"],
        sizes: ["XS", "S", "M", "L"],
        rating: { stars: 5, count: 42 },
        inStock: true,
        date: "2026-06-02",
        sales: 90
    },
    {
        id: 15,
        name: "Urban Cargo Joggers - Olive",
        category: "Joggers",
        fit: "Relaxed",
        gender: "Men",
        price: 1799,
        image: "images/ekkvastra_cargo.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#5c5a52", "#111111"],
        colorsName: ["olive", "black"],
        sizes: ["S", "M", "L", "XL"],
        rating: { stars: 4, count: 52 },
        inStock: true,
        date: "2026-06-07",
        sales: 145
    },
    {
        id: 16,
        name: "Women's Oversized Ribbed Sweatshirt",
        category: "Sweatshirts",
        fit: "Oversized",
        gender: "Women",
        price: 1499,
        image: "images/ekkvastra_hoodie.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#ffffff", "#d8d0c4"],
        colorsName: ["white", "beige"],
        sizes: ["XS", "S", "M", "L"],
        rating: { stars: 5, count: 37 },
        inStock: true,
        date: "2026-05-29",
        sales: 118
    },
    {
        id: 17,
        name: "Heavyweight Tee - Classic White",
        category: "Oversized Tees",
        fit: "Oversized",
        gender: "Unisex",
        price: 999,
        image: "images/ekkvastra_front_print_tee.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#ffffff", "#8a8a8a"],
        colorsName: ["white", "gray"],
        sizes: ["S", "M", "L", "XL"],
        rating: { stars: 4, count: 63 },
        inStock: true,
        date: "2026-06-16",
        sales: 200
    },
    {
        id: 18,
        name: "Premium Boxy Tee - Vintage Black",
        category: "Oversized Tees",
        fit: "Oversized",
        gender: "Unisex",
        price: 1099,
        image: "images/ekkvastra_front_print_tee.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#111111", "#8a8a8a"],
        colorsName: ["black", "gray"],
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        rating: { stars: 5, count: 142 },
        inStock: true,
        date: "2026-06-27",
        sales: 410,
        badge: "Best Seller"
    },
    {
        id: 19,
        name: "Heavy Cotton Jogger Shorts",
        category: "Shorts",
        fit: "Relaxed",
        gender: "Unisex",
        price: 1199,
        image: "images/ekkvastra_cargo.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#8a8a8a", "#5c5a52"],
        colorsName: ["gray", "olive"],
        sizes: ["S", "M", "L", "XL"],
        rating: { stars: 4, count: 31 },
        inStock: true,
        date: "2026-06-04",
        sales: 85
    },
    {
        id: 20,
        name: "Oversized Windbreaker - Royal Blue",
        category: "Jackets",
        fit: "Oversized",
        gender: "Unisex",
        price: 2699,
        image: "images/ekkvastra_hoodie.png",
        hoverImage: "images/ekkvastra_back_print_tee.png",
        colors: ["#1d4ed8", "#111111"],
        colorsName: ["blue", "black"],
        sizes: ["S", "M", "L", "XL"],
        rating: { stars: 5, count: 19 },
        inStock: true,
        date: "2026-06-26",
        sales: 62,
        badge: "New"
    }
];
